- type: entity
  parent: MobHuman
  id: EventRoleHumanCrashedCaptain
  categories: [ HideSpawnMenu ]
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    roleLoadout: [ JobCaptain ]

- type: entity
  parent: BaseEventRoleSpawn
  id: EventRoleSpawnCrashedCaptain
  name: crashed captain
  suffix: Event Role
  components:
  - type: Sprite
    sprite: Markers/jobs.rsi
    layers:
      - state: blue
      - state: captain
  - type: GhostRole
    name: crashed captain
    description: You are a member of the command team of the cargo ship Valiant. Something went horribly wrong and ship engines failed. You just barely managed to survive the crash. Figure out what to do to get home.
    rules: You are not an antagonist. Your goal is to get off the planet and get home. Follow the server rules unless told otherwise by an administrator.
    raffle:
      settings: default
  - type: GhostRoleMobSpawner
    prototype: EventRoleHumanCrashedCaptain

- type: entity
  parent: MobHuman
  id: EventRoleHumanCrashedEngineer
  categories: [ HideSpawnMenu ]
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    roleLoadout: [ JobStationEngineer ]

- type: entity
  parent: BaseEventRoleSpawn
  id: EventRoleSpawnCrashedEngineer
  name: crashed engineer
  suffix: Event Role
  components:
  - type: Sprite
    sprite: Markers/jobs.rsi
    layers:
      - state: blue
      - state: captain
  - type: GhostRole
    name: crashed engineer
    description: You are a member of the engineering team of the cargo ship Valiant. Something went horribly wrong and ship engines failed. You just barely managed to survive the crash. Figure out what to do to get home.
    rules: You are not an antagonist. Your goal is to get off the planet and get home. Follow the server rules unless told otherwise by an administrator.
    raffle:
      settings: default
  - type: GhostRoleMobSpawner
    prototype: EventRoleHumanCrashedEngineer

- type: entity
  parent: MobHuman
  id: EventRoleHumanCrashedDoctor
  categories: [ HideSpawnMenu ]
  components:
  - type: RandomHumanoidAppearance
    randomizeName: true
  - type: Loadout
    roleLoadout: [ JobMedicalDoctor ]

- type: entity
  parent: BaseEventRoleSpawn
  id: EventRoleSpawnCrashedDoctor
  name: crashed doctor
  suffix: Event Role
  components:
  - type: Sprite
    sprite: Markers/jobs.rsi
    layers:
      - state: blue
      - state: captain
  - type: GhostRole
    name: crashed doctor
    description: You are a member of the medical team of the cargo ship Valiant. Something went horribly wrong and ship engines failed. You just barely managed to survive the crash. Figure out what to do to get home.
    rules: You are not an antagonist. Your goal is to get off the planet and get home. Follow the server rules unless told otherwise by an administrator.
    raffle:
      settings: default
  - type: GhostRoleMobSpawner
    prototype: EventRoleHumanCrashedDoctor